"""The story spine: what to do next to advance the GAME, not just the party.

An idle loop that only grinds wilds is stuck forever. A real run measured this:
232 battles, level 19, fifteen minutes -- and still 0/8 badges, still on
Route 101. Levels are not progress; badges are.

What is data and what is derived
--------------------------------
The badge ORDER is the one thing the ROM does not state outright: gyms are
independent maps and nothing enumerates them in sequence, so ``SPINE`` below
lists them. Everything else is read:

* the leader's party, levels and types come from the decompilation's own
  trainer data (``docs/guide/trainers.json``, generated by
  ``scripts/build_guide.py`` out of ``src/data/trainer_parties.h``);
* the route to the gym comes from ``MapData.route`` over the real warp graph;
* how many badges we hold comes from the save block.

So this module knows the running order and nothing else. It cannot drift from
the ROM about what is IN a gym.

Tate and Liza share one gym and one badge; listing them separately is an
off-by-one that puts Wallace at badge 9 in a region that has 8.
"""

from __future__ import annotations

import json
import logging
from dataclasses import dataclass
from pathlib import Path

from . import paths

log = logging.getLogger(__name__)

#: Ordered gym spine: (badge number, leader label, gym map, town map).
#: The leader label is the decomp's own trainer-party key.
SPINE: tuple[tuple[int, str, str, str], ...] = (
    (1, "Roxanne", "RustboroCity_Gym", "RustboroCity"),
    (2, "Brawly", "DewfordTown_Gym", "DewfordTown"),
    (3, "Wattson", "MauvilleCity_Gym", "MauvilleCity"),
    (4, "Flannery", "LavaridgeTown_Gym_1F", "LavaridgeTown"),
    (5, "Norman", "PetalburgCity_Gym", "PetalburgCity"),
    (6, "Winona", "FortreeCity_Gym", "FortreeCity"),
    (7, "TateAndLiza", "MossdeepCity_Gym", "MossdeepCity"),
    (8, "Wallace", "SootopolisCity_Gym_1F", "SootopolisCity"),
)

@dataclass(frozen=True)
class StoryStep:
    """A prerequisite the game enforces before a road opens.

    Each one is a real gate found in the map data, with the variable or flag
    that guards it. Nothing here is a walkthrough instruction: the CONDITION is
    the game's own, and `pokeagent.gates` can cite the script that advances it.
    """

    detail: str
    kind: str               # "flag_unset" | "var_lt"
    name: str               # the FLAG_/VAR_ it tests
    value: int | None       # for var_lt
    map_name: str
    talk: tuple[int, int] | None   # who to talk to; None = arrive and let the
                                   # map's own frame script run
    #: A labelled option to pick when the conversation ends in a list box
    #: rather than YES/NO. Mr. Briney asks "Where are we bound?" with
    #: PETALBURG / SLATEPORT / CANCEL (MultichoiceList_00, script_menu.c:17),
    #: and answering it YES picks PETALBURG -- back the way we came.
    choice: str | None = None
    #: The whole box the ROM should be showing, so the label can be resolved
    #: without guessing. SLATEPORT alone sits at position 0 in some
    #: three-option lists and position 1 in others.
    choice_among: tuple[str, ...] | None = None
    #: A cell to STAND ON, for gates that are coord_events rather than
    #: conversations. `talk` walks adjacent and faces, which is exactly wrong
    #: for a trigger you have to step onto.
    stand: tuple[int, int] | None = None
    #: When to OFFER this step at all. The chain is flat but the game is not:
    #: the Go-Goggles exist only after badge 4, the harbor scene only after
    #: Mt. Pyre. Without a gate the first unmet step is offered forever even
    #: when nothing the player can do will meet it. Grammar:
    #:   "FLAG_X"      -- offer while the flag is SET
    #:   "!FLAG_X"     -- offer while the flag is UNSET
    #:   "VAR_X>=n"    -- offer while the var has reached n
    #: None offers unconditionally, as before.
    require: str | None = None


#: The gates between a fresh starter and the first gym, in the order the game
#: enforces them. Verified live: each one was the actual reason a journey
#: stopped, and clearing it opened the next road.
PROLOGUE: tuple[StoryStep, ...] = (
    # Birch will not hand over the Pokedex until the rival is beaten, and
    # OldaleTown_OnTransition keeps VAR_ROUTE102_ACCESSIBLE at 0 until then.
    StoryStep(
        "beat the rival on Route 103, so Birch will hand over the Pokedex",
        "flag_unset", "FLAG_DEFEATED_RIVAL_ROUTE103", None,
        "Route103", (10, 2),
    ),
    # The handover itself sets FLAG_ADVENTURE_STARTED and opens Route 102
    # (LittlerootTown_ProfessorBirchsLab/scripts.inc:131).
    StoryStep(
        "collect the Pokedex from Birch, which opens Route 102",
        "flag_unset", "FLAG_ADVENTURE_STARTED", None,
        "LittlerootTown_ProfessorBirchsLab", None,
    ),
    # Petalburg blocks its own west exit with four coord_events on
    # VAR_PETALBURG_STATE==0; seeing Norman sets it to 2
    # (PetalburgCity_Gym/scripts.inc:202) and the road to Route 104 opens.
    StoryStep(
        "see Norman in the Petalburg gym, which opens Route 104",
        "var_lt", "VAR_PETALBURG_STATE", 2,
        "PetalburgCity_Gym", (4, 3),
    ),
    # --- badge 2 needs a boat, and the boat needs the Devon errand ---
    # Traced live end to end; each condition is the game's own.
    #
    # Beating Roxanne leaves VAR_RUSTBORO_STATE at 2, and a coord_event at
    # (30,9) starts the stolen-goods errand. It is a WALK-ON trigger, not a
    # conversation, so the step just has to stand there.
    # GATED ON THE BADGE, because the coord_event will not fire without it.
    # `var_lt VAR_RUSTBORO_STATE 3` is also true at 0 and 1 -- i.e. before
    # Roxanne -- so this step read as pending from the moment the run reached
    # Rustboro and MASKED the gym behind it. The loop walked to (30,9), stood
    # on a trigger the game had not armed, gave up after six attempts and fell
    # through to training. Observed over an hour at 0 badges: Rustboro reached
    # repeatedly, `giving up on 'trigger the stolen Devon Goods errand'`, then
    # laps of Route 104/115/116 with the gym never once entered.
    StoryStep(
        "trigger the stolen Devon Goods errand in Rustboro",
        "var_lt", "VAR_RUSTBORO_STATE", 3,
        "RustboroCity", (30, 9),
        require="FLAG_BADGE01_GET",
    ),
    # The thief is a line-of-sight trainer in Rusturf Tunnel who drifts off his
    # map coordinate, so this is resolved live like Norman. Beating him hands
    # over ITEM_DEVON_GOODS and moves the state to 4.
    StoryStep(
        "get the Devon Goods back from the thief in Rusturf Tunnel",
        "var_lt", "VAR_RUSTBORO_STATE", 4,
        "RusturfTunnel", (14, 5),
        require="FLAG_BADGE01_GET",
    ),
    # Mr. Stone takes them, hands over the LETTER, and -- the part that
    # actually matters -- clears FLAG_HIDE_MR_BRINEY_ROUTE104_HOUSE
    # (RustboroCity_DevonCorp_3F/scripts.inc:63), which is what puts a boat on
    # the map at all.
    StoryStep(
        "deliver the goods to Mr. Stone, who unhides Mr. Briney",
        "var_lt", "VAR_RUSTBORO_STATE", 5,
        "RustboroCity_DevonCorp_3F", (15, 5),
        require="FLAG_BADGE01_GET",
    ),
    # CUT is picked up on the way past, not later. It is an unconditional gift
    # from the Cutter (RustboroCity_CuttersHouse/scripts.inc:9) a few steps from
    # the gym the run has just cleared, and it is the first HM the story needs
    # for traversal -- Route 116's cuttable trees stand between here and
    # several places the dex objective wants.
    StoryStep(
        "collect HM01 CUT from the Cutter in Rustboro",
        "flag_unset", "FLAG_RECEIVED_HM01", None,
        "RustboroCity_CuttersHouse", (7, 5),
    ),
    # And the crossing itself. FLAG_VISITED_DEWFORD_TOWN is the honest test:
    # the sail is a cutscene, so "did we end up there" beats any flag about
    # having asked.
    # GATED ON BRINEY EXISTING. Delivering the goods is what clears
    # FLAG_HIDE_MR_BRINEY_ROUTE104_HOUSE (cited above), so before the errand
    # his house is empty and this step sends the run to stand in front of
    # nobody. Unguarded, it simply inherited the stall from the step above it.
    StoryStep(
        "sail to Dewford with Mr. Briney",
        "flag_unset", "FLAG_VISITED_DEWFORD_TOWN", None,
        "Route104_MrBrineysHouse", (5, 3),
        require="!FLAG_HIDE_MR_BRINEY_ROUTE104_HOUSE",
    ),
    # Everything below is what stands between badge 2 and badge 3. The run
    # sat on the Dewford island for an hour cycling heal/train with the
    # objective "go to MauvilleCity_Gym", because there is no road: the only
    # way off is Mr. Briney's boat, and he will not sail anywhere new until
    # Steven has his letter.
    #
    # Getting to Steven is a genuine dungeon: his room is on Granite Cave 1F
    # but NOT reachable from the cave mouth. The route is 1F -> B1F -> B2F ->
    # B1F -> 1F, coming back up a different ladder into the western half.
    # route_legs() already plans that correctly; nothing knew to ask.
    # GATED ON HAVING GOT THERE. Granite Cave is on Route 106, off the Dewford
    # island, and the only way to the island is Briney's boat -- so before the
    # crossing this step names a destination with no route to it. Same shape as
    # the Devon steps above: an unreachable step is offered, the loop burns its
    # attempts on it, gives up, and trains instead of doing what it can.
    StoryStep(
        "deliver Steven's letter in Granite Cave",
        "flag_unset", "FLAG_DELIVERED_STEVEN_LETTER", None,
        "GraniteCave_StevensRoom", (7, 8),
        require="FLAG_VISITED_DEWFORD_TOWN",
    ),
    # DewfordTown_EventScript_Briney does
    # `goto_if_unset FLAG_DELIVERED_STEVEN_LETTER, ...ReturnToPetalburgPrompt`
    # -- so before the letter he offers only the way back, and after it the
    # PETALBURG / SLATEPORT / CANCEL list. Picking by LABEL matters: the
    # generic YES answer takes the first option, which sails us backwards.
    # The sail and the arrival are SEPARATE steps, because the boat does not
    # dock in the city: it lands on Route 109, the beach south of it, and
    # FLAG_VISITED_SLATEPORT_CITY only sets when the player walks north.
    #
    # Testing the sail with that flag read a SUCCESSFUL crossing as a failure
    # -- six of them -- and the loop gave up on the one step that led anywhere
    # and spent half an hour training in a cave. The honest test is the flag
    # the sail script itself sets on its last line
    # (DewfordTown_EventScript_SailToSlateport), confirmed live: after the
    # crossing the player is on Route109 with the boat flag set and the city
    # flag still clear.
    # SAME GATE: he is standing on Dewford, so this cannot be the next thing
    # to do until the run has actually crossed.
    StoryStep(
        "sail off the Dewford island with Mr. Briney",
        "flag_unset", "FLAG_HIDE_MR_BRINEY_BOAT_DEWFORD", None,
        "DewfordTown", (12, 9), choice="SLATEPORT",
        choice_among=("PETALBURG", "SLATEPORT", "CANCEL"),
        require="FLAG_VISITED_DEWFORD_TOWN",
    ),
    # No one to talk to: walking in is the whole step, and the city's own
    # ON_TRANSITION script sets the flag.
    StoryStep(
        "walk north into Slateport City",
        "flag_unset", "FLAG_VISITED_SLATEPORT_CITY", None,
        "SlateportCity", None,
        # PAST THE CROSSING TOO. Slateport is reached by Briney's boat; the
        # only land approach is Route 110 from Mauville, and Mauville early on
        # is behind Rusturf Tunnel's boulder, which needs a ROCK SMASH that is
        # itself past Slateport. So before the sail this is unreachable, and
        # offering it kept the run circling Route 115/116 with the Rustboro
        # gym never attempted.
        require="FLAG_VISITED_DEWFORD_TOWN",
    ),
    # Before the museum, the SHIPYARD -- and this one is not optional
    # politeness, it is the only thing that unseals the door.
    #
    # Three Team Aqua grunts stand at (29,27), (30,27) and (31,27), which are
    # the ONLY walkable approaches to the museum's two door tiles at (30,26)
    # and (31,26); everything else around them is wall. The museum is
    # therefore genuinely unreachable while they are there, and the loop
    # proved it the hard way -- 1171 failed attempts at
    # `no approach to warp (30,26)` in thirteen minutes.
    #
    # Talking to Dock in the shipyard sets FLAG_HIDE_EVIL_TEAM_SLATEPORT
    # alongside FLAG_DOCK_REJECTED_DEVON_GOODS
    # (SlateportCity_SternsShipyard_1F/scripts.inc:18), which removes them.
    # The rejection flag is the honest completion test: it is what that
    # conversation sets, and the grunt flag is shared with other events.
    StoryStep(
        "ask about the Devon Goods at Stern's Shipyard",
        "flag_unset", "FLAG_DOCK_REJECTED_DEVON_GOODS", None,
        "SlateportCity_SternsShipyard_1F", (5, 5),
        require="FLAG_VISITED_DEWFORD_TOWN",
    ),
    # The errand that started in Rustboro finally ends: Captain Stern takes
    # the DEVON GOODS in the Oceanic Museum
    # (SlateportCity_OceanicMuseum_2F/scripts.inc:90 sets the flag).
    StoryStep(
        "deliver the Devon Goods to Captain Stern",
        "flag_unset", "FLAG_DELIVERED_DEVON_GOODS", None,
        "SlateportCity_OceanicMuseum_2F", (13, 6),
        require="FLAG_VISITED_DEWFORD_TOWN",
    ),
    # And one more doorway held by people rather than walls. Wally and his
    # uncle stand at (8,6) and (9,6) in Mauville, which is the ONLY approach
    # to the gym door at (8,5) -- (7,5) and (9,5) are wall. Wally asks for a
    # battle (MSGBOX_YESNO, so the generic YES answer is right), and beating
    # TRAINER_WALLY_2 runs EventScript_DefeatedWally: `removeobject 6`,
    # `removeobject 7`, and the flag below. Until then the gym cannot be
    # entered at all, and `take_warp` reports the honest
    # "no approach to warp (8,5)".
    StoryStep(
        "battle Wally outside the Mauville gym",
        "flag_unset", "FLAG_DEFEATED_WALLY_MAUVILLE", None,
        "MauvilleCity", (8, 6),
    ),
    # Badge 4 is in Lavaridge, and there is no road. Route 112's seam to
    # Lavaridge (`left offset 40`) is on the far side of the mountain; the
    # southern half, which is what Mauville connects to, cannot reach it on
    # foot, and `route_legs` says so by returning nothing at all.
    #
    # The way through is the cable car: Route 112 (28,27)/(29,27) -> the
    # station, up to Mt. Chimney, and down Jagged Pass, which re-enters
    # Route 112 at (6,46)/(7,46) on the Lavaridge side.
    #
    # The attendant asks YES/NO, so the generic answer is right here. The
    # completion test is Mt. Chimney's OWN ON_TRANSITION script
    # (MtChimney_MapScript1_15CF87) setting VAR_JAGGED_PASS_ASH_WEATHER -- the
    # map's statement that we arrived, rather than a flag about having asked.
    # And before any of that, ROCK SMASH -- because the road north out of
    # Mauville is not blocked by a story gate, it is blocked by two rocks.
    #
    # The objects at Route 111 (18,101) and (19,100) render as NPCs to
    # anything reading live positions, which is how they were nearly
    # diagnosed as wandering trainers boxing the player in. They are
    # `OBJ_EVENT_GFX_BREAKABLE_ROCK`, they sit either side of the only
    # corridor north, and they do not move. `find_path` was right every time.
    #
    # MauvilleCity_House1 (4,4) hands over HM06 unconditionally.
    StoryStep(
        "collect HM06 ROCK SMASH in Mauville",
        "flag_unset", "FLAG_RECEIVED_HM06", None,
        "MauvilleCity_House1", (4, 4),
    ),
    # Badge 4 is in Lavaridge, and the way there is Route 112's northern
    # half -- which has a direct `left offset 40` seam to Lavaridge. The
    # southern half, the one Mauville connects to, cannot reach it: the
    # mountain splits the route. FIERY PATH bridges the two halves (both its
    # warps land on Route 112), and its through-route is held by six
    # `S_PushableBoulder`, which is STRENGTH.
    #
    # HM04 is in Rusturf Tunnel from the boyfriend at (23,5), behind
    # FLAG_HIDE_BOYFRIEND_RUSTURF_TUNNEL -- and a `S_BreakableRock` at (24,5),
    # which is now smashable. The tunnel is already on the run's map.
    #
    # A retraction that earns its lines: an earlier revision here claimed both
    # Meteor Falls doors were across water and the whole Mt. Chimney chain was
    # post-badge-4. The measurements were real and the model was wrong --
    # elevation 0 was treated as a bridge instead of a transition, which cut
    # every level change in Hoenn, made Route 114's door read as a 52-cell
    # pocket, and manufactured a circular dependency the game does not have.
    # The chain below is the game's own, verified end to end on a fork:
    # Meteor Falls (on foot via Fallarbor) -> cable car -> Mt. Chimney ->
    # Jagged Pass -> Lavaridge.
    StoryStep(
        "collect HM04 STRENGTH in Rusturf Tunnel",
        "flag_unset", "FLAG_RECEIVED_HM04", None,
        "RusturfTunnel", (23, 5),
    ),
    # Mt. Chimney IS on the road to badge 4, and removing these was a mistake
    # worth recording. Lavaridge's seam from Route 112 (west edge y=47-53)
    # sits in a 397-cell component that neither the Mauville side (298 cells)
    # nor Fiery Path's northern landing (91) can reach. What reaches it is
    # JAGGED PASS, which comes down from Mt. Chimney -- so the cable car is
    # the way, the Team Magma grunts blocking it are the gate, and Meteor
    # Falls is what moves them.
    StoryStep(
        "witness Team Magma at Meteor Falls, which clears the cable car road",
        "var_lt", "VAR_METEOR_FALLS_STATE", 1,
        "MeteorFalls_1F_1R", None, stand=(14, 18),
    ),
    # VAR_JAGGED_PASS_ASH_WEATHER resets to 0 on every Route 112 transition
    # (Route112/scripts.inc:7) -- it answers "am I on the mountain RIGHT NOW",
    # not "have I ever ridden". Ungated, this step re-arms the moment the run
    # walks down Jagged Pass and sends it straight back up the mountain,
    # forever.
    #
    # But the gate must be BADGE 4, not the leader. The cable car is also the
    # only TRANSPORT to the Lavaridge side: the seam component is reachable
    # solely by descending Jagged Pass, and the router cannot plan through a
    # scripted ride. Gated on the leader, the run beat him, wandered down to
    # train, and then had no offered step that could ever take it back up --
    # "no walkable route from Route102 to LavaridgeTown_Gym_1F" eight times
    # and a shrug. Offered until the badge is won, the step doubles as the
    # ride home whenever the run finds itself on the wrong side of the
    # mountain. Descending afterwards needs no help: Route 112's ledges drop
    # one-way into the Mauville side.
    # The CONDITION is the town's own visited flag, because it is the only
    # persistent fact the ride produces. The first candidate -- the ash var --
    # is 1 only while standing on the mountain, so the step re-armed inside
    # the gym, dragged the run out to the station, up, down, back to the gym
    # and around again: a nine-leg orbit it executed flawlessly six times
    # before giving up. Riding is DONE when Lavaridge has been entered once
    # (LavaridgeTown/scripts.inc:7 sets the flag on first transition).
    StoryStep(
        "ride the cable car up Mt. Chimney",
        "flag_unset", "FLAG_VISITED_LAVARIDGE_TOWN", None,
        "Route112_CableCarStation", (6, 6),
        require="!FLAG_DEFEATED_LAVARIDGE_GYM",
    ),
    # magma_chimney.inc:86; the summit fight that clears the mountain.
    StoryStep(
        "beat the team leader on Mt. Chimney",
        "flag_unset", "FLAG_DEFEATED_EVIL_TEAM_MT_CHIMNEY", None,
        "MtChimney", (13, 6),
    ),
    # LavaridgeTown/scripts.inc:84-97, armed by beating Flannery
    # (LavaridgeTown_Gym_1F/scripts.inc:81). OnFrame -- walking in is enough.
    StoryStep(
        "collect the Go-Goggles from the rival in Lavaridge",
        "flag_unset", "FLAG_RECEIVED_GO_GOGGLES", None,
        "LavaridgeTown", None,
        require="FLAG_DEFEATED_LAVARIDGE_GYM",
    ),
    # PetalburgCity_WallysHouse/scripts.inc:9,22-24 -- Surf after Norman.
    StoryStep(
        "collect HM03 SURF from Wally's father in Petalburg",
        "flag_unset", "FLAG_RECEIVED_HM_SURF", None,
        "PetalburgCity_WallysHouse", (3, 4),
        require="FLAG_DEFEATED_PETALBURG_GYM",
    ),
    # Route118/map.json:298-325 -- the Steven scene on the east bank.
    StoryStep(
        "cross Route 118 and meet Steven on the east bank",
        "var_lt", "VAR_ROUTE118_STATE", 1,
        "Route118", None, stand=(43, 11),
        require="FLAG_RECEIVED_HM_SURF",
    ),
    # Route119_WeatherInstitute_2F/scripts.inc:30-46: grunt 5 at (4,6);
    # beating him hands over CASTFORM and frees the institute.
    StoryStep(
        "take the Weather Institute back from the grunts",
        "var_lt", "VAR_WEATHER_INSTITUTE_STATE", 1,
        "Route119_WeatherInstitute_2F", (4, 6),
        require="FLAG_RECEIVED_HM_SURF",
    ),
    # Route119/map.json:522-541; the rival hands over HM02 FLY
    # (Route119/scripts.inc:150-151).
    StoryStep(
        "beat the rival north of the Weather Institute for HM02 FLY",
        "var_lt", "VAR_ROUTE119_STATE", 1,
        "Route119", None, stand=(25, 31),
        require="FLAG_RECEIVED_HM_SURF",
    ),
    # Route120/scripts.inc:196-236: Steven, the Kecleon fight, and the Scope.
    StoryStep(
        "get the Devon Scope from Steven on Route 120",
        "flag_unset", "FLAG_RECEIVED_DEVON_SCOPE", None,
        "Route120", (13, 15), choice="YES",
        require="FLAG_RECEIVED_HM02",
    ),
    # ---- tools that are themselves encounter METHODS ---------------------
    #
    # Gated on `field:FLY` -- a party member KNOWING Fly, with the badge that
    # permits it -- and not on owning HM02. That distinction is the whole
    # history of these three steps: gated on the item they fired the moment
    # HM02 entered the bag and sent the run walking from Route 119 across a
    # river to Route 118 while Winona's gym sat two maps away; gated on BADGE06
    # they fired again and filled the log with "could not cross the D seam"
    # while badges 7 and 8 went unattempted. They were pulled out entirely for
    # a while because of it.
    #
    # Behind FLY each is a hop, and each is worth real dex: a rod decides which
    # fishing slots exist at all (src/wild_encounter.c:200-235, ~30 species
    # live only there) and the Safari Zone -- sixteen species behind NO badge --
    # refuses entry without the Pokeblock Case
    # (Route121_SafariZoneEntrance/scripts.inc:61-64).

    # Route118/scripts.inc:9-26
    StoryStep(
        "take the GOOD ROD from the fisherman on Route 118",
        "flag_unset", "FLAG_RECEIVED_GOOD_ROD", None,
        "Route118", (28, 8), choice="YES",
        require="field:FLY",
    ),
    # DewfordTown/scripts.inc:73-90
    StoryStep(
        "take the OLD ROD from the fisherman in Dewford",
        "flag_unset", "FLAG_RECEIVED_OLD_ROD", None,
        "DewfordTown", (12, 14), choice="YES",
        require="field:FLY",
    ),
    # SlateportCity_ContestLobby/scripts.inc:102-111 -- handed over
    # unconditionally, and the Safari Zone refuses entry without it.
    StoryStep(
        "collect the POKEBLOCK CASE from the girl in Slateport's contest lobby",
        "flag_unset", "FLAG_RECEIVED_POKEBLOCK_CASE", None,
        "SlateportCity_ContestLobby", (1, 5),
        require="field:FLY",
    ),

    # GraniteCave_1F/scripts.inc:7-13 -- a HIKER at (36,9) who hands HM05
    # over unconditionally, with no YES/NO to answer. The run walked past him
    # THREE times delivering Steven's letter and never had FLASH, which is
    # what VictoryRoad_B1F and _B2F both declare `requires_flash` for
    # (pret/data/maps/VictoryRoad_B1F/map.json:7). Nothing was asking.
    StoryStep(
        "take HM05 FLASH from the hiker in Granite Cave",
        "flag_unset", "FLAG_RECEIVED_HM05", None,
        "GraniteCave_1F", (36, 9),
        require="field:FLY",
    ),
    # MossdeepCity_House3/scripts.inc:7-16 -- a FISHERMAN at (4,4), MSGBOX_YESNO,
    # no gate of any kind in the script. This is the highest-value collectible
    # left in the game for a dex run: the rod held decides which fishing slots
    # can be rolled at all (src/wild_encounter.c:200-235), and roughly thirty
    # species live ONLY in slots a SUPER ROD reaches. Gated on badge 7 here
    # only because that is the beat that brings the run to Mossdeep anyway --
    # the errand is free once you are standing in the town.
    StoryStep(
        "take the SUPER ROD from the fisherman in Mossdeep",
        "flag_unset", "FLAG_RECEIVED_SUPER_ROD", None,
        "MossdeepCity_House3", (4, 4), choice="YES",
        require="FLAG_BADGE07_GET",
    ),

    # FortreeCity/scripts.inc:53-91: the invisible Kecleon on the gym bridge.
    StoryStep(
        "flush the Kecleon off the Fortree gym bridge",
        "flag_unset", "FLAG_KECLEON_FLED_FORTREE", None,
        "FortreeCity", (25, 8), choice="YES",
        require="FLAG_RECEIVED_DEVON_SCOPE",
    ),
    # MtPyre_Summit/scripts.inc:70-77; the orb theft arms Slateport Harbor.
    StoryStep(
        "witness the orb theft on Mt. Pyre's summit",
        "var_lt", "VAR_MT_PYRE_STATE", 1,
        "MtPyre_Summit", None, stand=(23, 7),
        require="FLAG_BADGE06_GET",
    ),
    # SlateportCity_Harbor/scripts.inc:47-82; sets the hideout-opening flags.
    StoryStep(
        "watch the submarine theft at Slateport Harbor",
        "var_lt", "VAR_SLATEPORT_HARBOR_STATE", 2,
        "SlateportCity_Harbor", None, stand=(8, 12),
        require="VAR_SLATEPORT_HARBOR_STATE>=1",
    ),
    # AquaHideout_B2F/scripts.inc:25-68; the hideout chase ends here.
    StoryStep(
        "chase the team through the Lilycove hideout",
        "flag_unset", "FLAG_EVIL_TEAM_ESCAPED_IN_SUBMARINE", None,
        "AquaHideout_B2F", (23, 19),
        require="VAR_SLATEPORT_HARBOR_STATE>=2",
    ),
    # MossdeepCity_StevensHouse/scripts.inc:25-48 -- no gate at all; Steven
    # hands Dive to whoever walks in. Ordered after badge 7 because that is
    # when Dive becomes USABLE (src/field_control_avatar.c:521).
    StoryStep(
        "collect HM08 DIVE from Steven's house in Mossdeep",
        "flag_unset", "FLAG_RECEIVED_HM08", None,
        "MossdeepCity_StevensHouse", None,
        require="FLAG_BADGE07_GET",
    ),
    # SeafloorCavern_Room9/scripts.inc:195-218; the climax that reopens
    # Sootopolis.
    StoryStep(
        "follow the team to the bottom of the Seafloor Cavern",
        "flag_unset", "FLAG_LEGEND_ESCAPED_SEAFLOOR_CAVERN", None,
        "SeafloorCavern_Room9", None,
        require="FLAG_RECEIVED_HM08",
    ),
    # data/item_ball_scripts.inc:477-479 -- HM07 on the way down.
    StoryStep(
        "pick up HM07 WATERFALL in the Cave of Origin",
        "flag_unset", "FLAG_ITEM_CAVE_OF_ORIGIN_B3F_1", None,
        "CaveOfOrigin_B3F", (6, 5),
        require="FLAG_LEGEND_ESCAPED_SEAFLOOR_CAVERN",
    ),
    # CaveOfOrigin_B4F/scripts.inc:52-79: Kyogre L45, and every Sootopolis
    # door reopens behind it.
    StoryStep(
        "face Kyogre at the bottom of the Cave of Origin",
        "var_lt", "VAR_CAVE_OF_ORIGIN_B4F_STATE", 1,
        "CaveOfOrigin_B4F", None, stand=(9, 13),
        require="FLAG_LEGEND_ESCAPED_SEAFLOOR_CAVERN",
    ),
)

#: Lead at least this far above the leader's strongest mon before walking in.
#: Not a superstition: a leader's ace carries a type advantage and a real
#: moveset, and the loop's own tactics can only pick from what it knows.
LEVEL_MARGIN = 1

#: How much stronger the WHOLE party must get before re-challenging a leader
#: that already beat us. Lead level alone is a bad predictor: this run walked
#: an L53 MIGHTYENA into Wallace three times and lost every one, because the
#: other five sat at 42-49 with nothing super-effective. Each loss also halves
#: the money, which is what drained the run to 62 and stopped all catching.
RETRY_PARTY_GAIN = 8

#: Never walk into a gym below this fraction of max HP.
HEALTHY = 0.85


@dataclass(frozen=True)
class Objective:
    """One concrete thing to do now, with the reason attached."""

    kind: str          # "train" | "travel" | "heal" | "fight_leader" | "done"
    detail: str
    badge: int | None = None
    leader: str | None = None
    map_name: str | None = None
    target_level: int | None = None

    def as_dict(self) -> dict:
        return {
            "kind": self.kind, "detail": self.detail, "badge": self.badge,
            "leader": self.leader, "map": self.map_name,
            "target_level": self.target_level,
        }


class Quest:
    """Turns 'how many badges do I have' into 'what should I do next'."""

    def __init__(self, driver, trainers=None):
        self.d = driver
        self._trainers = trainers
        self.last_reason = ""

    # ---- data ----------------------------------------------------------

    @property
    def trainers(self) -> dict:
        """The generated trainer table, or {} when the guide has not been
        built. Absent data must degrade to 'no level target', never to a
        guess about what a leader brings."""
        if self._trainers is None:
            path = Path(paths.TOOL_DIR) / "docs" / "gen3" / "guide" / "trainers.json"
            try:
                self._trainers = json.loads(path.read_text())
            except Exception as err:  # noqa: BLE001
                log.debug("no trainer table (%s); level targets unavailable", err)
                self._trainers = {}
        return self._trainers

    def leader_party(self, leader: str) -> list[dict]:
        row = self.trainers.get(leader) or {}
        return list(row.get("party") or ())

    def leader_level(self, leader: str) -> int | None:
        party = self.leader_party(leader)
        return max((m["level"] for m in party), default=None) or None

    # ---- state ---------------------------------------------------------

    def badges(self) -> int:
        """How many badges are held.

        `GameState.badges()` returns the NAMES of the badges held, so the
        obvious `int(...)` raises TypeError -- and a bare `except` turned that
        into a permanent 0. The run beat Roxanne, FLAG_BADGE01_GET was set, and
        the loop re-challenged her every step for the rest of the night because
        its own counter said zero. A swallowed exception is worse than a crash.
        """
        try:
            held = self.d.state.badges()
        except Exception as err:  # noqa: BLE001 - no save block on a boot screen
            log.warning("cannot read badges (%s); assuming none", err)
            return 0
        if isinstance(held, int):
            return held
        try:
            return len(held)
        except TypeError:
            log.warning("badges() returned %r; assuming none", held)
            return 0

    def next_gym(self) -> tuple[int, str, str, str] | None:
        """The first gym whose badge we do not hold.

        Keyed on the COUNT rather than on individual badge flags: the count is
        what the save block exposes cheaply, and the spine is ordered, so
        holding n badges means the next gym is the (n+1)th.
        """
        have = self.badges()
        for row in SPINE:
            if row[0] > have:
                return row
        return None

    def party(self) -> list:
        try:
            return [m for m in self.d.state.party() if not m.is_egg]
        except Exception:  # noqa: BLE001
            return []

    def live_cell(self, map_name: str, static_cell: tuple[int, int]
                  ) -> tuple[int, int]:
        """Where that object actually IS, not where the map file puts it.

        Scripts move people at runtime. Norman's map entry puts him at (4,3),
        deep inside a 9x112 gym whose rooms are joined by internal warps; for
        the introduction the game stands him at (4,107), four tiles from the
        door. Walking to the static cell is therefore impossible, and the loop
        spent five minutes failing to reach a man standing next to it.

        The live object list is matched by LOCAL ID -- the map's Nth
        object_event is local id N+1 -- so this is exact rather than
        nearest-neighbour guesswork. Off-map (planning), the static cell is
        all there is and is returned unchanged.
        """
        if self.d.map_name() != map_name:
            return static_cell
        try:
            info = self.d.nav.info(map_name)
            objects = list(getattr(info, "objects", ()) or ())
        except Exception:  # noqa: BLE001
            return static_cell
        local_id = None
        for i, obj in enumerate(objects):
            if (int(obj["x"]), int(obj["y"])) == tuple(static_cell):
                local_id = i + 1
                break
        if local_id is None:
            return static_cell
        try:
            for npc in self.d.live_npcs():
                if npc.get("player"):
                    continue
                if int(npc.get("local_id", -1)) == local_id:
                    return (int(npc["x"]), int(npc["y"]))
        except Exception as err:  # noqa: BLE001
            log.debug("live npc read failed on %s: %s", map_name, err)
        return static_cell

    def leader_cell(self, gym_map: str, leader: str) -> tuple[int, int] | None:
        """Where the leader stands, from the gym map's own object_events.

        Matched on the object's SCRIPT label rather than its graphics id: the
        script is named after the leader
        (`RustboroCity_Gym_EventScript_Roxanne`) while graphics ids are shared,
        and for the double-battle gym there are two sprites to find. Returns
        the first match, so Tate answers for "TateAndLiza" -- talking to
        either one starts the same double battle.
        """
        try:
            info = self.d.nav.info(gym_map)
        except Exception as err:  # noqa: BLE001
            log.debug("no map info for %s: %s", gym_map, err)
            return None
        wanted = [leader.lower()]
        if leader.lower() == "tateandliza":
            wanted = ["tate", "liza"]
        for obj in getattr(info, "objects", ()) or ():
            script = (obj.get("script") or "").lower()
            if any(f"eventscript_{w}" in script for w in wanted):
                return (int(obj["x"]), int(obj["y"]))
        return None

    def lead_level(self) -> int:
        party = self.party()
        return max((m.level for m in party), default=0)

    # ---- the decision --------------------------------------------------

    def pending_story(self) -> StoryStep | None:
        """The first prologue gate still shut, or None.

        Checked before any gym: a party at the right level still cannot reach
        Rustboro while Petalburg's west exit is closed, and the failure looks
        like a pathing bug rather than a story one.

        THE PROLOGUE IS A SEQUENCE, so an unfinished step that is not yet
        offered means the story is BLOCKED -- not that the next one is due.
        This used to `continue` past such a step and hand back something from
        further down the chain, which is how a fresh run at 0 badges was told
        to "walk north into Slateport City" (a boat ride away) and then to
        "battle Wally outside the Mauville gym" (two towns past that). It
        chased each in turn, gave up, and ground Route 115 for an hour with
        the Rustboro gym unvisited.

        Returning None here is what lets the caller fall through to the badge,
        which is usually the very thing that opens the blocked step.
        """
        for step in PROLOGUE:
            try:
                if step.kind == "flag_unset":
                    done = bool(self.d.state.flag(step.name))
                elif step.kind == "var_lt":
                    done = int(self.d.state.var(step.name)) >= int(step.value)
                else:
                    done = True
                if done:
                    continue
                # Incomplete. Actionable only if its own gate is open.
                return step if self._step_offered(step) else None
            except Exception as err:  # noqa: BLE001 - an unreadable save block
                log.debug("cannot evaluate %s: %s", step.name, err)
                return None
        return None

    def _step_offered(self, step) -> bool:
        """Whether a step's `require` gate holds. Unreadable means not offered:
        a step we cannot evaluate is a step we cannot act on either."""
        req = getattr(step, "require", None)
        if not req:
            return True
        try:
            if req.startswith("!"):
                return not self.d.state.flag(req[1:])
            # CAN-USE, not merely own. `field:FLY` asks whether a party member
            # actually knows the move AND the badge that permits it is held --
            # which is what `field_moves()` answers. Owning HM02 is not being
            # able to fly, and gating the collectibles on the ITEM sent the run
            # walking across Hoenn twice.
            if req.startswith("field:"):
                move = req.split(":", 1)[1].upper()
                return self.d.field_moves().get(move) is not None
            if ">=" in req:
                name, n = req.split(">=")
                return int(self.d.state.var(name)) >= int(n)
            return bool(self.d.state.flag(req))
        except Exception as err:  # noqa: BLE001
            log.debug("cannot evaluate require %r: %s", req, err)
            return False

    def _loss_path(self):
        from pathlib import Path

        return Path(str(self.d.state_path) + ".losses.json")

    def _losses(self) -> dict:
        import json

        try:
            return json.loads(self._loss_path().read_text())
        except Exception:  # noqa: BLE001
            return {}

    def party_total(self) -> int:
        return sum(int(m.level or 0) for m in self.party())

    def note_loss(self, leader: str) -> None:
        """Remember how strong we were when this leader beat us."""
        import json

        data = self._losses()
        data[str(leader).upper()] = self.party_total()
        try:
            self._loss_path().write_text(json.dumps(data))
        except Exception:  # noqa: BLE001
            pass

    def retry_bar(self, leader: str):
        """Party total we must exceed before challenging `leader` again."""
        # Case-normalised: the quest tables say "Wallace" while callers and
        # journals say "WALLACE", and a mismatch silently disarms the bar.
        bar = self._losses().get(str(leader).upper())
        return None if bar is None else int(bar) + RETRY_PARTY_GAIN

    def next_objective(self, skip_story: bool = False) -> Objective:
        """What to do right now, and why.

        Ordered so that the reason is always the most specific true one:
        finished > need levels > hurt > not there yet > fight.

        `skip_story` asks the same question WITHOUT the prologue, for a caller
        that has already tried the pending step and found it unreachable. The
        loop used to fall from an abandoned story step straight to training,
        so an unreachable prologue entry hid the gym behind it indefinitely --
        the badge that would have unlocked the step was never attempted.
        """
        story = None if skip_story else self.pending_story()
        if story is not None:
            self.last_reason = f"{story.name} not satisfied"
            return Objective(
                "story", story.detail, map_name=story.map_name,
            )

        gym = self.next_gym()
        if gym is None:
            self.last_reason = "all badges held"
            return Objective("done", "all 8 badges held; the Elite Four is next")

        badge, leader, gym_map, town = gym
        want = self.leader_level(leader)
        have = self.lead_level()

        if want is not None and have < want + LEVEL_MARGIN:
            self.last_reason = (
                f"lead is L{have}; {leader}'s ace is L{want}"
            )
            return Objective(
                "train",
                f"train to L{want + LEVEL_MARGIN} for {leader} "
                f"(ace L{want})",
                badge=badge, leader=leader, map_name=gym_map,
                target_level=want + LEVEL_MARGIN,
            )

        # DO NOT RE-RUN A FIGHT WE HAVE ALREADY LOST AT THIS STRENGTH.
        # Losing halves the money, and the money is what buys the balls the
        # Pokedex needs, so a leader we cannot beat is a drain rather than a
        # gamble. Train until the WHOLE party is materially stronger.
        bar = self.retry_bar(leader)
        total = self.party_total()
        if bar is not None and total < bar:
            self.last_reason = (
                f"{leader} already beat this party (total {total} < {bar})"
            )
            return Objective(
                "train",
                f"train: {leader} beat us at party total {total}; "
                f"need {bar}",
                badge=badge, leader=leader, map_name=gym_map,
                target_level=have + 2,
            )

        party = self.party()
        hurt = [m for m in party if m.max_hp and m.hp / m.max_hp < HEALTHY]
        if hurt:
            who = ", ".join(str(m.nickname) for m in hurt[:3])
            self.last_reason = f"{who} below {HEALTHY:.0%}"
            return Objective(
                "heal", f"heal before {leader} ({who} hurt)",
                badge=badge, leader=leader, map_name=gym_map,
            )

        here = self.d.map_name()
        if here != gym_map:
            self.last_reason = f"at {here}, gym is {gym_map}"
            return Objective(
                "travel", f"go to {gym_map} for badge {badge} ({leader})",
                badge=badge, leader=leader, map_name=gym_map,
            )

        self.last_reason = f"inside {gym_map} at L{have}"
        return Objective(
            "fight_leader", f"beat {leader} for badge {badge}",
            badge=badge, leader=leader, map_name=gym_map,
        )

    # ---- reporting -----------------------------------------------------

    def as_dict(self) -> dict:
        obj = self.next_objective()
        gym = self.next_gym()
        out = {
            "badges": self.badges(),
            "objective": obj.as_dict(),
            "reason": self.last_reason,
        }
        if gym:
            badge, leader, gym_map, town = gym
            out["next_gym"] = {
                "badge": badge, "leader": leader, "map": gym_map,
                "town": town,
                "ace_level": self.leader_level(leader),
                "party": self.leader_party(leader),
            }
        return out

    def summary(self) -> str:
        obj = self.next_objective()
        return f"{self.badges()}/8 badges -- {obj.detail} [{self.last_reason}]"
